[package]
name = "activitypub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
base64 = "0.21.0"
bytes = "1.4.0"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
derive_builder = "0.12.0"
displaydoc = "0.2.4"
dyn-clone = "1.0.11"
enum_delegate = "0.2.0"
futures-core = { version = "0.3.28", default-features = false }
http = "0.2.9"
http-signature-normalization = "0.7.0"
http-signature-normalization-reqwest = { version = "0.8.0", default-features = false, features = [
	"sha-2",
	"middleware",
] }
httpdate = "1.0.2"
itertools = "0.10.5"
once_cell = "1.17.1"
openssl = "0.10.52"
parse-display = "0.8.0"
pin-project-lite = "0.2.9"
regex = { version = "1.8.1", default-features = false, features = ["std"] }
reqwest = { version = "0.11.17", features = ["json", "stream"] }
reqwest-middleware = "0.2.2"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
sha2 = "0.10.6"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["test-util", "macros"] }
tracing = "0.1.37"
url = { version = "2.3.1", features = ["serde"] }
