[package]
name = "backend"
version = "0.0.0"
edition = "2021"
default-run = "backend"

[workspace]

members = ["crates/*"]

[profile.development]
inherits = "dev"

[profile.production]
inherits = "release"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = { path = "crates/server" }
logging = { path = "crates/logging" }
queue  = { path = "crates/queue" }
config = { path = "crates/config" }
macros = { path = "crates/macros" }
lazy_static = "1.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = { version = "1.28.1", features = ["full"] }
anyhow = "1.0.71"

[dev-dependencies]
