[package]
name = "backend"
version = "0.0.0"
edition = "2021"
default-run = "backend"

[workspace]

members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
serde = { version = "1.0.160", features = [ "derive" ] }
serde_yaml = "0.9.21"
server = { path = "crates/server" }

[dev-dependencies]
