[package]
name = "backend"
version = "0.0.0"
edition = "2021"
default-run = "backend"

[workspace]

members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = { path = "crates/server" }

[dev-dependencies]
