calckey:
  domain: example.tld

  server:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  worker:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: example.tld
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: example-tld-certificate
      hosts:
        - example.tld

elasticsearch:
  enabled: false

postgresql:
  auth:
    password: CHANGEME
    postgresPassword: CHANGEME
  primary:
    persistence:
      enabled: true
      storageClass: example-storage-class
      size: 25Gi
    resources:
      requests:
        cpu: 0.25
        memory: 256Mi
      limits:
        cpu: 0.5
        memory: 512Mi
  metrics:
    enabled: true

redis:
  auth:
    password: CHANGEME
  master:
    resources:
      requests:
        cpu: 0.25
        memory: 256Mi
      limits:
        cpu: 0.5
        memory: 256Mi
    persistence:
      storageClass: example-storage-class
      size: 10Gi
  replica:
    replicaCount: 0
  metrics:
    enabled: true
